export const LOAD_MENU = 'LOAD_WP_MENU'
export const LOAD_MENU_DONE = 'LOAD_WP_MENU_DONE'
export const LOAD_MENU_ERROR = 'LOAD_WP_MENU_ERROR'

export const LOAD_TAXONOMY = 'LOAD_WP_TAXONOMY'
export const LOAD_TAXONOMY_DONE = 'LOAD_WP_TAXONOMY_DONE'
export const LOAD_TAXONOMY_ERROR = 'LOAD_WP_TAXONOMY_ERROR'

export const LOAD_POSTS = 'LOAD_WP_POSTS'
export const LOAD_POSTS_DONE = 'LOAD_WP_POSTS_DONE'
export const LOAD_POSTS_ERROR = 'LOAD_WP_POSTS_ERROR'

export const LOAD_CUSTOM_POSTS_BY_TAXONOMY = 'LOAD_CUSTOM_POSTS_BY_TAXONOMY'
export const LOAD_CUSTOM_POSTS_BY_TAXONOMY_DONE = 'LOAD_CUSTOM_POSTS_BY_TAXONOMY_DONE'
export const LOAD_CUSTOM_POSTS_BY_TAXONOMY_ERROR = 'LOAD_CUSTOM_POSTS_BY_TAXONOMY_ERROR'

export const LOAD_POST = 'LOAD_WP_POST'
export const LOAD_POST_DONE = 'LOAD_WP_POST_DONE'
export const LOAD_POST_ERROR = 'LOAD_WP_POST_ERROR'

export const LOAD_PAGE = 'LOAD_WP_PAGE'
export const LOAD_PAGE_DONE = 'LOAD_WP_PAGE_DONE'
export const LOAD_PAGE_ERROR = 'LOAD_WP_PAGE_ERROR'


export const LOAD_PAGES = 'LOAD_PAGES'
export const LOAD_PAGES_DONE = 'LOAD_PAGES_DONE'
export const LOAD_PAGES_ERROR = 'LOAD_PAGES_ERROR'


export const LOAD_MEDIA = 'LOAD_MEDIA'
export const LOAD_MEDIA_DONE = 'LOAD_MEDIA_DONE'
export const LOAD_MEDIA_ERROR = 'LOAD_MEDIA_ERROR'


export const LOAD_CHILD_PAGES = 'LOAD_CHILD_PAGES'
export const LOAD_CHILD_PAGES_DONE = 'LOAD_CHILD_PAGES_DONE'
export const LOAD_CHILD_PAGES_ERROR = 'LOAD_CHILD_PAGES_ERROR'

export const CLEAN_PAGE_DATA = 'CLEAN_PAGE_DATA'


export const LOAD_SEARCH = 'LOAD_SEARCH'
export const LOAD_SEARCH_DONE = 'LOAD_SEARCH_DONE'
export const LOAD_SEARCH_ERROR = 'LOAD_SEARCH_ERROR'
